name: Trivy IaC Scan

on:
  push:
    paths:
      - '**.tf'
      - '**.yaml'
      - '**.yml'
      - '**/Dockerfile'
  pull_request:
    paths:
      - '**.tf'
      - '**.yaml'
      - '**.yml'
      - '**/Dockerfile'

jobs:
  trivy-iac-scan:
    runs-on: ubuntu-latest
    name: Trivy IaC Misconfiguration Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Run Trivy IaC scan and save output
        run: |
          trivy config . --format json --output trivy-results.json

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac-report
          path: trivy-results.json
