name: Trivy IaC Scan

on:
  push:
    paths:
      - '**.tf'
      - '**.yaml'
      - '**.yml'
      - '**/Dockerfile'
  pull_request:
    paths:
      - '**.tf'
      - '**.yaml'
      - '**.yml'
      - '**/Dockerfile'

jobs:
  trivy-iac-scan:
    runs-on: ubuntu-latest
    name: Trivy IaC Misconfiguration Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      -curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin


      - name: Run Trivy IaC scan and save output
        run: |
          trivy config . --format json --output trivy-results.json

      - name: Upload Trivy Report 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac-report
          path: trivy-results.json
